prometheusOperator:
  podAnnotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::972582919197:role/vruddha-monitoring  
prometheus:  
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::972582919197:role/vruddha-monitoring  
  serviceAccount:
     annotations: 
      eks.amazonaws.com/role-arn: arn:aws:iam::972582919197:role/vruddha-monitoring    
  prometheusSpec:
    replicas: 1      # work in High-Availability mode
    retention: 12h 
    image:
      tag: v2.31.1
    thanos:
      tag: v0.13.0   # a specific version of Thanos
      objectStorageConfig: # blob storage configuration to upload metrics 
        key: thanos-storage-config.yaml
        name: thanos-storage-config
      #secretProviderClass:
      #  provider: gcp
        #parameters:
        #   objects: |
        
        #      - objectName: "MySecret"
        #        objectType: "secretsmanager"
        #region: "us-west-2"
      #objectStorageConfigFile: /var/secrets/object-store.yaml
  thanosService: 
    enabled: true      
  thanosServiceMonitor:
    enabled: true
  #thanosIngress:
  #  enabled: true
    # ingressClassName: nginx
  #  annotations:
  #    kubernetes.io/ingress.class: nginx
  
  #    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  #    nginx.ingress.kubernetes.io/grpc-backend: "true"
  #    nginx.ingress.kubernetes.io/protocol: h2c
  #    nginx.ingress.kubernetes.io/backend-protocol: GRPC
  #    nginx.ingress.kubernetes.io/proxy-read-timeout: GRPC
  #  hosts:
  #    - thanos.xyz.com
  #  paths:
  
  #    - /
  #  pathType: ImplementationSpecific
  #ingress:
  #  enabled: true
    # ingressClassName: nginx
  #  annotations:
  #    kubernetes.io/ingress.class: nginx
  #    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  
  #    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  #  hosts:
  #    - prometheus.xyz.com
  #  paths:
  #    - /
alertmanager:
  enabled: true
  alertmanagerSpec:
    image:
      tag: v0.21.0
grafana:
  enabled: true
  replicas: 1
  image:
    repository: grafana/grafana
    tag: 7.1.0